// src/data.js
export const cities = [
    { name: "Aberdeen", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Aylesbury", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Banbury", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Basingstoke", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Basildon", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bedford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Belfast", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Birkenhead", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Birmingham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Blackburn", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Blackpool", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bolton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bournemouth", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bradford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bracknell", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Brighton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bristol", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Burnley", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Burton upon Trent", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Bury", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Cambridge", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Carlisle", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Cardiff", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Chatham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Chelmsford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Chester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Chesterfield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Chichester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Cleethorpes", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Colchester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Coventry", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Crawley", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Darlington", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Derby", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Doncaster", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Dover", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Dudley", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Dundee", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Durham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Eastbourne", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Edinburgh", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Exeter", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Gateshead", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Gillingham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Glasgow", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Gloucester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Gravesend", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Great Yarmouth", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Grimsby", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Guildford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Hartlepool", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Hastings", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Hemel Hempstead", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Hereford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "High Wycombe", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Huddersfield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Hull", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Ipswich", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Keighley", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Kingston upon Hull", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Lancaster", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Leeds", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Leicester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Lincoln", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Liverpool", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "London", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Luton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Macclesfield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Maidstone", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Manchester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Mansfield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Middlesbrough", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Milton Keynes", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Newcastle upon Tyne", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Newport", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Northampton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Northwich", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Norwich", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Nottingham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Nuneaton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Oldham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Oxford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Peterborough", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Plymouth", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Poole", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Portsmouth", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Preston", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Reading", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Redhill", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Rochdale", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Rotherham", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Scunthorpe", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Sheffield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Shrewsbury", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Slough", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Solihull", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Southampton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Southend", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Southport", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "St Albans", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Stevenage", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Stoke-on-Trent", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Sunderland", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Swansea", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Swindon", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Telford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Wakefield", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Walsall", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Warrington", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Watford", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Wellingborough", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "West Bromwich", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Wigan", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Wolverhampton", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Worcester", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "Worthing", options: ["Part Time", "Driver", "Accommodation"] },
    { name: "York", options: ["Part Time", "Driver", "Accommodation"] }
  ];
  export default cities;  